version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      spring-boot-major-upgrades:
        patterns:
          - "org.springframework.boot:*"
        update-types:
          - "major"
      spring-boot-minor-upgrades:
        patterns:
          - "org.springframework.boot:*"
        update-types:
          - "minor"
      spring-boot-patch-upgrades:
        patterns:
          - "org.springframework.boot:*"
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
